module.exports = [
  `CREATE TABLE IF NOT EXISTS public_users (
    id INT NOT NULL AUTO_INCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    module TEXT NOT NULL,
    role TEXT NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_public_users_email (email),
    CHECK (module IN ('sgs-erc', 'sgs-fms', 'super')),
    CHECK (role IN ('super_admin', 'admin', 'engineer', 'client', 'supervisor'))
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS public_refresh_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_public_refresh_tokens_user_id (user_id),
    CONSTRAINT fk_public_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES public_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS public_audit_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id INT NULL,
    module TEXT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NULL,
    payload JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_public_audit_logs_user_id (user_id),
    CONSTRAINT fk_public_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES public_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS erc_call_logs (
    id INT NOT NULL AUTO_INCREMENT,
    reference_no TEXT NOT NULL,
    caller_name TEXT NOT NULL,
    contact TEXT NOT NULL,
    location TEXT NOT NULL,
    issue_type TEXT NOT NULL,
    priority TEXT NOT NULL,
    status TEXT NOT NULL,
    assigned_to INT NULL,
    description TEXT NOT NULL,
    created_by INT NOT NULL,
    vehicle_number TEXT NULL,
    severity TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_erc_call_logs_reference_no (reference_no),
    KEY idx_erc_call_logs_status (status),
    KEY idx_erc_call_logs_priority (priority),
    KEY idx_erc_call_logs_assigned_to (assigned_to),
    KEY idx_erc_call_logs_created_by (created_by),
    CONSTRAINT fk_erc_call_logs_assigned_to FOREIGN KEY (assigned_to) REFERENCES public_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_erc_call_logs_created_by FOREIGN KEY (created_by) REFERENCES public_users(id) ON DELETE RESTRICT,
    CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    CHECK (status IN ('open', 'hold', 'in_progress', 'resolved', 'closed'))
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS erc_call_updates (
    id INT NOT NULL AUTO_INCREMENT,
    call_log_id INT NOT NULL,
    updated_by INT NOT NULL,
    status TEXT NOT NULL,
    comment TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_erc_call_updates_call_log_id (call_log_id),
    KEY idx_erc_call_updates_updated_by (updated_by),
    CONSTRAINT fk_erc_call_updates_call_log_id FOREIGN KEY (call_log_id) REFERENCES erc_call_logs(id) ON DELETE CASCADE,
    CONSTRAINT fk_erc_call_updates_updated_by FOREIGN KEY (updated_by) REFERENCES public_users(id) ON DELETE RESTRICT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS erc_attachments (
    id INT NOT NULL AUTO_INCREMENT,
    call_log_id INT NOT NULL,
    file_path TEXT NOT NULL,
    uploaded_by INT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_erc_attachments_call_log_id (call_log_id),
    KEY idx_erc_attachments_uploaded_by (uploaded_by),
    CONSTRAINT fk_erc_attachments_call_log_id FOREIGN KEY (call_log_id) REFERENCES erc_call_logs(id) ON DELETE CASCADE,
    CONSTRAINT fk_erc_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES public_users(id) ON DELETE RESTRICT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS erc_notifications (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    message TEXT NOT NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_erc_notifications_user_id (user_id),
    KEY idx_erc_notifications_created_at (created_at),
    CONSTRAINT fk_erc_notifications_user_id FOREIGN KEY (user_id) REFERENCES public_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_call_logs (
    id INT NOT NULL AUTO_INCREMENT,
    reference_no TEXT NOT NULL,
    call_no TEXT NULL,
    month TEXT NULL,
    call_open_dt TIMESTAMP NULL,
    division TEXT NULL,
    area TEXT NULL,
    machine TEXT NULL,
    asset_no TEXT NULL,
    equipment_name TEXT NULL,
    asset_non_asset TEXT NULL,
    nature_of_call TEXT NULL,
    type_of_assets TEXT NULL,
    call_category TEXT NULL,
    equipment_materials TEXT NULL,
    repeated_call TEXT NULL,
    problem_reported_by TEXT NULL,
    call_description TEXT NULL,
    call_attended_by TEXT NULL,
    call_attend_dt TIMESTAMP NULL,
    action_taken TEXT NULL,
    call_closed_dt TIMESTAMP NULL,
    response_time_min DECIMAL(12,2) NULL,
    resolution_time_min DECIMAL(12,2) NULL,
    downtime_min DECIMAL(12,2) NULL,
    pending_side TEXT NULL,
    remarks TEXT NULL,
    import_batch_id BIGINT NULL,
    client_request_id TEXT NULL,
    caller_name TEXT NOT NULL,
    contact TEXT NOT NULL,
    location TEXT NOT NULL,
    issue_type TEXT NOT NULL,
    priority TEXT NOT NULL,
    status TEXT NOT NULL,
    assigned_to INT NULL,
    description TEXT NOT NULL,
    created_by INT NOT NULL,
    vehicle_number TEXT NULL,
    severity TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fms_call_logs_reference_no (reference_no),
    KEY idx_fms_call_logs_status (status),
    KEY idx_fms_call_logs_priority (priority),
    KEY idx_fms_call_logs_assigned_to (assigned_to),
    KEY idx_fms_call_logs_created_by (created_by),
    CONSTRAINT fk_fms_call_logs_assigned_to FOREIGN KEY (assigned_to) REFERENCES public_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_fms_call_logs_created_by FOREIGN KEY (created_by) REFERENCES public_users(id) ON DELETE RESTRICT,
    CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    CHECK (status IN ('open', 'hold', 'in_progress', 'resolved', 'closed'))
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_call_updates (
    id INT NOT NULL AUTO_INCREMENT,
    call_log_id INT NOT NULL,
    updated_by INT NOT NULL,
    status TEXT NOT NULL,
    comment TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fms_call_updates_call_log_id (call_log_id),
    KEY idx_fms_call_updates_updated_by (updated_by),
    CONSTRAINT fk_fms_call_updates_call_log_id FOREIGN KEY (call_log_id) REFERENCES fms_call_logs(id) ON DELETE CASCADE,
    CONSTRAINT fk_fms_call_updates_updated_by FOREIGN KEY (updated_by) REFERENCES public_users(id) ON DELETE RESTRICT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_attachments (
    id INT NOT NULL AUTO_INCREMENT,
    call_log_id INT NOT NULL,
    file_path TEXT NOT NULL,
    uploaded_by INT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fms_attachments_call_log_id (call_log_id),
    KEY idx_fms_attachments_uploaded_by (uploaded_by),
    CONSTRAINT fk_fms_attachments_call_log_id FOREIGN KEY (call_log_id) REFERENCES fms_call_logs(id) ON DELETE CASCADE,
    CONSTRAINT fk_fms_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES public_users(id) ON DELETE RESTRICT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_notifications (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    message TEXT NOT NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fms_notifications_user_id (user_id),
    KEY idx_fms_notifications_created_at (created_at),
    CONSTRAINT fk_fms_notifications_user_id FOREIGN KEY (user_id) REFERENCES public_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_maintenance_schedules (
    id INT NOT NULL AUTO_INCREMENT,
    vehicle_number TEXT NOT NULL,
    planned_date DATE NOT NULL,
    notes TEXT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_by INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fms_maintenance_schedules_planned_date (planned_date),
    KEY idx_fms_maintenance_schedules_created_by (created_by),
    CONSTRAINT fk_fms_maintenance_schedules_created_by FOREIGN KEY (created_by) REFERENCES public_users(id) ON DELETE RESTRICT,
    CHECK (status IN ('scheduled', 'in_progress', 'completed'))
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`
  ,
  `CREATE TABLE IF NOT EXISTS fms_import_batches (
    id BIGINT NOT NULL AUTO_INCREMENT,
    import_key VARCHAR(128) NOT NULL,
    file_name TEXT NOT NULL,
    uploader_id INT NULL,
    uploader_name VARCHAR(255) NULL,
    file_size_bytes BIGINT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    imported_rows INT NOT NULL DEFAULT 0,
    skipped_rows INT NOT NULL DEFAULT 0,
    failed_rows INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'processing',
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    rolled_back_at TIMESTAMP NULL DEFAULT NULL,
    rolled_back_by INT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fms_import_batches_import_key (import_key),
    KEY idx_fms_import_batches_uploader_id (uploader_id),
    KEY idx_fms_import_batches_uploaded_at (uploaded_at),
    KEY idx_fms_import_batches_status (status),
    CONSTRAINT fk_fms_import_batches_uploader_id FOREIGN KEY (uploader_id) REFERENCES public_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_fms_import_batches_rolled_back_by FOREIGN KEY (rolled_back_by) REFERENCES public_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_import_errors (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_id BIGINT NOT NULL,
    row_number INT NOT NULL,
    incident_no TEXT NULL,
    error_message TEXT NOT NULL,
    row_data JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fms_import_errors_batch_id (batch_id),
    KEY idx_fms_import_errors_row_number (row_number),
    CONSTRAINT fk_fms_import_errors_batch_id FOREIGN KEY (batch_id) REFERENCES fms_import_batches(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_divisions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fms_divisions_name (name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_areas (
    id BIGINT NOT NULL AUTO_INCREMENT,
    division_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fms_areas_division_name (division_name, name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_call_categories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fms_call_categories_name (name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS fms_asset_types (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fms_asset_types_name (name)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `ALTER TABLE fms_call_logs
    ADD COLUMN IF NOT EXISTS call_no TEXT NULL,
    ADD COLUMN IF NOT EXISTS month TEXT NULL,
    ADD COLUMN IF NOT EXISTS call_open_dt TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS division TEXT NULL,
    ADD COLUMN IF NOT EXISTS area TEXT NULL,
    ADD COLUMN IF NOT EXISTS machine TEXT NULL,
    ADD COLUMN IF NOT EXISTS asset_no TEXT NULL,
    ADD COLUMN IF NOT EXISTS equipment_name TEXT NULL,
    ADD COLUMN IF NOT EXISTS asset_non_asset TEXT NULL,
    ADD COLUMN IF NOT EXISTS nature_of_call TEXT NULL,
    ADD COLUMN IF NOT EXISTS type_of_assets TEXT NULL,
    ADD COLUMN IF NOT EXISTS call_category TEXT NULL,
    ADD COLUMN IF NOT EXISTS equipment_materials TEXT NULL,
    ADD COLUMN IF NOT EXISTS repeated_call TEXT NULL,
    ADD COLUMN IF NOT EXISTS problem_reported_by TEXT NULL,
    ADD COLUMN IF NOT EXISTS call_description TEXT NULL,
    ADD COLUMN IF NOT EXISTS call_attended_by TEXT NULL,
    ADD COLUMN IF NOT EXISTS call_attend_dt TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS action_taken TEXT NULL,
    ADD COLUMN IF NOT EXISTS call_closed_dt TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS response_time_min DECIMAL(12,2) NULL,
    ADD COLUMN IF NOT EXISTS resolution_time_min DECIMAL(12,2) NULL,
    ADD COLUMN IF NOT EXISTS downtime_min DECIMAL(12,2) NULL,
    ADD COLUMN IF NOT EXISTS pending_side TEXT NULL,
    ADD COLUMN IF NOT EXISTS remarks TEXT NULL,
    ADD COLUMN IF NOT EXISTS import_batch_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS client_request_id TEXT NULL`,
  `ALTER TABLE fms_call_logs
    ADD CONSTRAINT fk_fms_call_logs_import_batch_id FOREIGN KEY (import_batch_id) REFERENCES fms_import_batches(id) ON DELETE SET NULL`
];
